# Generated by Django 2.2.1 on 2020-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='time',
            field=models.CharField(choices=[('10-11', '10-11'), ('11-12', '11-12'), ('12-13', '12-13'), ('13-14', '13-14'), ('14-15', '14-15')], default='', max_length=5),
        ),
    ]
